### ISSUE TITLE
Distribute components over separate dockerfiles

### ISSUE THREAD

**Issue by reinvantveer** [histograph/deploy#5]
Redis will start but seems unavailable to histograph core for some reason or other. Will take more time to figure out.

**Comment by wires** [comment]
docker runs only one process, `RUN /etc/init.d/redis start` is a build step, doesn't happen inside the image. see https://github.com/phusion/passenger-docker for a solution, it uses `my_init` and `runit` instead of init, see https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by wires** [comment]
some more info here
- http://tech.paulcz.net/2014/12/multi-process-docker-images-done-right/
- https://blog.phusion.nl/2015/01/20/baseimage-docker-fat-containers-treating-containers-vms/
- http://stackoverflow.com/questions/19948149/can-i-run-multiple-programs-in-a-docker-container
